### ISSUE TITLE
Square video format

### ISSUE THREAD

**Issue by activha** [widgetfactory/wf_responsive_widgets#10]
As the plugin defaults to 16/9 there is a big padding bottom for square videos.

The idea was to set a padding-bottom: calc(var(--aspect-ratio, .5625) * 100%);  with a style="--aspect-ratio: 3 / 4;" as explained [here](https://css-tricks.com/fluid-width-video/)

is it possible to implement ?

**Comment by ryandemmer** [comment]
Added in commit - https://github.com/widgetfactory/wf_responsive_widgets/commit/3d158d099939948635d1d0f00a9d7778970153e9
