### ISSUE TITLE
No effet with new versions of JCE

### ISSUE THREAD

**Issue by pulsarinformatique** [widgetfactory/wf_responsive_widgets#17]
Hi
On Joomla 3.10.11, JCE 2.9.32 this plugin has no effect on the JCE youtube iframes. There is no wf-responsive class added.
I use Helix Ultimate Framework 1.1.3

Thanks

cyril

**Comment by ryandemmer** [comment]
This has been tested and is working in the setup you describe. Please ensure the plugin is enabled after install.

**Comment by pulsarinformatique** [comment]
you are right, it just doesn't work with Seblod :(

**Comment by pulsarinformatique** [comment]
Even if I put your plugin in the first position it doesn't work once the page displays a seblod enhanced article
