### ISSUE TITLE
Also affecting Soundcloud embeds

### ISSUE THREAD

**Issue by lowpeter** [widgetfactory/wf_responsive_widgets#2]
Hi,

I have added this  to a Joomla 3 website and it is awesome. All the youtube embeds (with previously defined width and height) are now responsive - which is what I wanted. However it would seem that the extra div is also being placed around Soundcloud embeds which is making them 16:9 in shape which is giving them much more height than I wanted (I did not want soundcloud to be touched as the embed is already 100% in width and has the correct height).

I do not know how your code is working,  but I can see that it seems to have something related to youtube, vimeo and dialy motion, but somehow it is not being applied to just these embeds, but is being applied to more <i frames>.

The extra div seems to not being applied to bandcamp embeds which I think is correct.

Any ideas on how to fix this? Any help would be appreciated.

As a side note all the embeds were showing  with scroll bars, so in the responsive css I added an overflow: hidden !important; line whiich fixed that issue (unable to check what happens on a ii device).

Please let me know if you require any further information. Many  thanks.

**Comment by lowpeter** [comment]
Hi, further to this I now think that it is affecting pretty much all i frame embeds including the bandcamp. It is like the plugin is is not taking notice of whether the embed is only vimeo, daily motion or youtube. I only want this plugin to do the youtube and other videos, but not audio. Hope this is possible.

Many thanks. As before, please let me know if you need any more info.

**Comment by ryandemmer** [comment]
Fixed in https://github.com/widgetfactory/wf_responsive_widgets/commit/4ff8facb31a1d0d96665a06e367553aab9abedb8
