### ISSUE TITLE
Version 1.0.12?

### ISSUE THREAD

**Issue by jjnxpct** [widgetfactory/wf_responsive_widgets#8]
Hi Ryan, the version of the responsive_widgets plugin here on GitHub is 1.0.6. Correct? Buton two of our sites we somehow have a 1.0.12 version installed?? 

If we want the latest version, is the one we can download here the most recent? (1.0.6)?

**Comment by ryandemmer** [comment]
Please download the latest version here - https://github.com/widgetfactory/wf_responsive_widgets/releases

**Comment by jjnxpct** [comment]
Thanks!
